name: Post welcome comment
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write

jobs:
  welcome:
    name: post welcome message
    runs-on: ubuntu-latest
    steps:
      - name: Comment
        run: echo hi this is a mock message
      - name: Comment Pull request
        run: gh pr comment "$PR_URL" --body "Welcome to the repository!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_requests.html_url }}        
